//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workers
    {
        public int id { get; set; }
        public Nullable<int> id_role { get; set; }
        public string fio { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> id_entry { get; set; }
        public string photo { get; set; }
    
        public virtual entry entry { get; set; }
        public virtual role role { get; set; }
    }
}
